packages:
  - apps/*
  - contracts
  - tests/*

minimumReleaseAge: 10080
minimumReleaseAgeExclude: []
onlyBuiltDependencies:
  - esbuild
strictDepBuilds: false
saveExact: true
preferFrozenLockfile: true
allowBuilds:
  '@asyncapi/cli': set this to true or false
  '@hyperjump/json-pointer': set this to true or false
  '@hyperjump/json-schema': set this to true or false
  '@hyperjump/json-schema-core': set this to true or false
  '@hyperjump/pact': set this to true or false
  '@scarf/scarf': set this to true or false
  esbuild: set this to true or false
  vue-demi: set this to true or false
  yarn: set this to true or false
